replicaCount: 2

image:
  repository: me-west1-docker.pkg.dev/mongodb-nodeapp-project/docker-image/nodeapp
  tag: v2
  pullPolicy: Always

service:
  name: nodeapp-service
  type: NodePort
  port: 3000
  annotations:
    backendConfig: my-backend-config

hpa:
  name: nodeapp-hpa
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  name: nodeapp-ingress
  enabled: true
  annotations: 
    ingressClass: "nginx"
    sslRedirect: "true"
  tlsSecretName: nodeapp-tls-secret
  path: /
  pathType: Prefix

backendConfig:
  name: my-backend-config
  timeoutSec: 40
  connectionDrainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /

secret:
  name: nodeapp-tls-secret
  tlsCrt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3RENDQXRTZ0F3SUJBZ0lVZVNvaVdGdm81VENyV2E5NG5oMG41anpnVXZVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NURUxNQWtHQTFVRUJoTUNTVXd4RERBS0JnTlZCQWdNQTFSTVZqRVJNQThHQTFVRUJ3d0lVMjl0WlVOcApkSGt4RWpBUUJnTlZCQW9NQ1UxNVEyOXRjR0Z1ZVRFVE1CRUdBMVVFQ3d3S1RYbEVhWFpwYzJsdmJqRVlNQllHCkExVUVBd3dQZDNkM0xtTnZiWEJoYm5rdVkyOXRNQjRYRFRJME1ERXdOVEl4TWpBME1sb1hEVEkxTURFd05ESXgKTWpBME1sb3djVEVMTUFrR0ExVUVCaE1DU1V3eEREQUtCZ05WQkFnTUExUk1WakVSTUE4R0ExVUVCd3dJVTI5dApaVU5wZEhreEVqQVFCZ05WQkFvTUNVMTVRMjl0Y0dGdWVURVRNQkVHQTFVRUN3d0tUWGxFYVhacGMybHZiakVZCk1CWUdBMVVFQXd3UGQzZDNMbU52YlhCaGJua3VZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBdnovQnNjTUhZT1oreUMzcGN5aWRpTmp0VG5XMDhaaUpsMnV0K05Wc0xTK2VRTzZGa21wcwpRVVFnUzJEUmR4WDAwRXg4S3ZmUGVGVHQ3VVZxQWpXR2pocjBHd0Rrb3ZBdDMvcldSRDc1WmdsYkZoeTVkWWI5CkdrUTNIVG02Y21nc2h6Y2J0TjE2VGZpdm5oUUZ4QnlQbEZuYTFTUkhrN29ncEJpRElCaXlRbWp6UzlLVDlHTWgKNGVPZXB2c3RKK1RqcWdNalJxVWFoSG9xYTRRbWxhTTdWYU91RHB0VERTbnJGRFl3N05OdFRCUzMvQlN1cURmWAp2TnpsOUNmTW1XYVhKNFVLUUp6aWFyZXFVLzhPT0Q4NGtxUENyVVRLNFp3VEpPdXlRc25OUnZpZitONEdhUU1yCkVOK0puY0xRMVBBU250dlpmK3grd3ZCcm9sZER3a3pWTFFJREFRQUJvM3d3ZWpBT0JnTlZIUThCQWY4RUJBTUMKQTRnd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdOQVlEVlIwUkJDMHdLNElQZDNkM0xtTnZiWEJoYm5rdQpZMjl0Z2d0amIyMXdZVzU1TG1OdmJZSUxZMjl0Y0dGdWVTNXVaWFF3SFFZRFZSME9CQllFRkVCNzlaZkZkSWp5CktmdUdGN1YxcnllMDVJck9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNZWWhPY0k3M3htdlZKOTMxV1Bhb20KS1B2Qm9YMTZoQjN6dUdOWFJUUDZpNTVjNFZRbHViY2VnNm5mNzNpMUxUemE2UWdRZmF1UGVTYXkyZnRqWnRvZgptemVEanNYNVVVMTZrQU9TSEsyd1dCbVdEL2RsMThjM05oSjhoMG9xUk5XQ3lpZWFXdCtXT3RyMWhpUk5XaFJuCkMyL1BQMEZKVGNPUGoyc3hCVURCTFc2OVBtVFkyamtFOUg2dnpoZzlCRWlGUEtWL0QyVGM5WU9BYS92WFczZ1QKTThYb0ZwNVpFWk5TcVczU2lzaW1sNzlsakFxZkM3ak9CekVRYmdrQXFkNTFQV1NQWkxBQ3c0MWx2R1lOOWtmUAp5cDR5UWg2NXZ0SEp0MDB5N3d2cWY4L2VWcWNoY3RGUmdRQTRYSTBHd1dQdFdvbE4vSDVzNGE3L2EyL0l4QUYvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  tlsKey: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQy9QOEd4d3dkZzVuN0kKTGVsektKMkkyTzFPZGJUeG1JbVhhNjM0MVd3dEw1NUE3b1dTYW14QlJDQkxZTkYzRmZUUVRId3E5ODk0Vk8zdApSV29DTllhT0d2UWJBT1NpOEMzZit0WkVQdmxtQ1ZzV0hMbDFodjBhUkRjZE9icHlhQ3lITnh1MDNYcE4rSytlCkZBWEVISStVV2RyVkpFZVR1aUNrR0lNZ0dMSkNhUE5MMHBQMFl5SGg0NTZtK3kwbjVPT3FBeU5HcFJxRWVpcHIKaENhVm96dFZvNjRPbTFNTktlc1VOakRzMDIxTUZMZjhGSzZvTjllODNPWDBKOHlaWnBjbmhRcEFuT0pxdDZwVAovdzQ0UHppU284S3RSTXJobkJNazY3SkN5YzFHK0ovNDNnWnBBeXNRMzRtZHd0RFU4QktlMjlsLzdIN0M4R3VpClYwUENUTlV0QWdNQkFBRUNnZ0VBRitxdGVxRkE1amVWQWN3cURtWjFJdlM3NG95NlN0OVFUNkVkOGNrZzNOckEKWCs3a1FkM3d1VTIvZXlXNXREcUk4ZGFxellYTmlvY1dkUTV4OWlKQytEajdMM2hTWDJVSlc2SUhFeVJMOUp4MQphV1BBdHFlaHRkdnpoNEpkWkdyT0xMK3h4WkhQOW5uRDNwRXk4bVkrOTJhd1JPampVYUJjYmlFSm51VXZ2N21nCkhYQkdKaHVIT24xYXkyRkhhMWgrbFZ3STEzcUFmMEhFTGZiY0V5MUJnL3c2VzNZNjE1ZXM1bW1sQy9ReFZhQkYKQ3NWdVJEZnVVS29uZEVQV3gzeVc4WnpZMXlrKzBsZnpRakNhMHBUeWVTcDFybUhlbzlLc2JiZ0ZKa3krUkY0VQowbEVhdXdPY0Ztb3l1TEgrZzZBL0hOaEM2TWIzeDU1N2tVV0Q5NUY2OFFLQmdRRElsSzVFSy9TZ2FEWXFXVXdQCmppWlJBOEoyc3dFNVJpcE51bVpRODd1bkFEWmw2MndCdzFCeStJTFl6YjFaTlBManEzcFlyMm9oY3FTOEt0eTIKa3VBOFFOVjg4akprMldjdzZ3WHVIOXVVUSs4UHBoUTlTUStKdVE5VXFadlZIMERMMG1INzFPWllUNFJ3NmRzMQpzUmtIRWJwRGh6dEVicWJrRWtDbE5uQWQ4UUtCZ1FEMEZ3ZjJaOXBvSklERlJGR2dLWEpzSSs4QWliSkx2OEtWCndaV1hTT3RjV2c3S2VHU2ltNzI3YXh1dU9EVTRJbHV1TUw1SmRST1IxYm9QblFIdVBwVFZ3cXR5S1lnZ080cFoKejQ0eWhyeU5jbnNMQWlTOHpYblRtZ2Rkbko1c2NUUnVDVVFPd3F5bEZvTFU5TEpKdG12SU5rckZITnY0M1VOZwp5cGtaV00wZS9RS0JnRUIxYjI5ZkJOVkx5Q1JoNEF5YnJQcWFEN05mb1VRTHBXcW5QVnhFaDRpS2kvREM4RW04CnY2ekM2aUhNTkU1bnNxcXhuN2JDWUlQeE9MbHp1TXcvZFNwSDE1TzRyYk0xSG5GZEJlSFpnUklycHJiTHMzTmkKZUVqVkhQVWpNSDRUOWhuS09Velp4VkNaOVVEb0ZsY3gyNDRuQjBuT09xQ3FRcDNHczlta0hmR3hBb0dCQU9HSwp5bnUvK010VU4zeVFKVkIyRzltYTFvUkx0K2xRbHEra1FlS1pxWWtiV2lGeVg2TDFmN3JIUEx1ZUNtY0ZNR3ZqCmRHRVNBblExNWdmNVQwaGlvVXBuNTkzRVRKbGtDdkh6M0hRSmxmNnBjdEo0TjVRUjFXbFdJVW81cHhXVEFSeFEKQ1lnT0VGTTNXc3NHRkJ3U3FNTkdqNDVWblZqMnN3U2tFQldndldETkFvR0JBS3k1VCt3Qkx2aW51Z2dlM29weQpBTTNPdGw5OVpVQ1dzV3Z3dTh5U0gwZkpkTnBhcW5KT01oeEpvRTUvM3FLY2RZZVVka1N0a3EvU0RsaUJBZnJyCmRQbTdESHV3Z092VW9QN1BFTmpodVkyUFJRN3lROVhNczFvS1l5a2NFRk55RTlQYVFuOTE5aU41NjJrT1A1UmMKQVJrV3NCdVVvR0NJdWVoSHdGUlVmNGNLCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
