apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secret.tlsCrt }}
  tls.key: {{ .Values.secret.tlsKey }}
