apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.service.annotations.backendConfig }}"}'
spec:
  selector:
    app: nodeapp-deployment
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
